# CircleCI Pre-Built Docker Images
# - https://circleci.com/docs/2.0/circleci-images/

# CirlceCI Configuration
version: 2

# References
references:

  working_directory: &working_directory
    ~/app

  image_node: &image_node
    image: circleci/node:8.11.2

  image_node_browsers: &image_node_browsers
    image: circleci/node:8.11.2-browsers

  job_defaults: &job_defaults
    working_directory: *working_directory
    docker:
      - *image_node

  job_defaults_browsers: &job_defaults_browsers
    working_directory: *working_directory
    docker:
      - *image_node_browsers

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      key: cache-{{ .Branch }}-{{ checksum "package.json" }}

  restore_npm_cache_peer: &restore_npm_cache_peer
    restore_cache:
      key: dependency-cache-peer-{{ checksum "package.json" }}


# Jobs
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *restore_npm_cache_peer
      - run:
          name: Install NodeJS Dependencies via NPM
          command: npm install
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build dist and cache
          command: npm run ng:build
      - save_cache:
          key: dist-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - dist
  test_spec:
    <<: *job_defaults_browsers
    steps:
      - checkout
      - *restore_npm_cache
      - *restore_npm_cache_peer
      - run:
          name: Test Spec
          command: npm run test -- --single-run=true --progress=false --code-coverage --log-level=DEBUG
      - store_artifacts:
          path: coverage/ts
          destination: coverage
  test_cypress:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dist-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: npm run cy:verify
      - run:
          name: Start
          command: npm run start:ci
      - run:
          name: Run Cypress
          command: npm run test:cypress
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *restore_npm_cache_peer
      - run:
          name: Lint TypeScript
          command: npm run ng:lint

# Workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_spec:
          requires:
            - build
      - test_cypress:
          requires:
            - build
      - lint:
          requires:
            - build
